### ISSUE TITLE
Server API Address not being saved to preferences

### ISSUE THREAD

**Issue by haspden** [haspden/INFLITE-TYPE-ONE-Hammerhead-CGM#1]
When updating the user's Nightscout server address, the app always pulls from the DEFAULT_SERVER_ADDRESS rather than the updated user's server address from the front end. The changes are saved to the preferences but the saved value is not used for the data pull.

**Comment by valterc** [comment]
That is likely because the SDK elements run in another process/app. I will fix that :)
